# Generated by Django 2.2.3 on 2020-05-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'T1'), (2, 'T2'), (3, 'T3')], null=True, verbose_name='级别'),
        ),
    ]
